export class Job{
    jobId!:number;
    companyName!:string;
    experience!:number;
    jobTitle!:string;
    linkedinUrl!:string;
    joiningDate!:string;
    description!:string;
    postedDate!:string;
    mandatorySkills!:string;
    optionalSkills!:string;
    certification!:string;
    expiryOfRole!:string;
    isActive!:boolean;
    createdBy!:number;
    createdOn!:string;
    modifiedBy!:number;
    modifiedOn!:string;
}